version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: gabrielsouzaa/api-fornecedores
    ports:
      - 10000:10000
    links:
      - mongodb